import type { TestingConsoleSnapshot } from "@/types/testing";

export const mockTestingConsoleSnapshot: TestingConsoleSnapshot = {
  eventId: "event-summit",
  overallStatus: "warn",
  goNoGo: "monitor",
  recoveryMode: "producer_intervention",
  whiteLabelBackupProvider: "zoom",
  whiteLabelBackupLabel: "Agency Event OS Backup Room",
  whiteLabelBackupUrl: "https://backup.example.com/client-safe-room",
  whiteLabelBackupEnabled: true,
  generatedAt: "2026-05-18T16:15:00.000Z",
  checks: [
    {
      id: "check-browser",
      label: "Browser compatibility",
      description: "Confirms supported browser, secure context, and required media APIs.",
      status: "pass",
      severity: "medium",
      recommendedAction: "No action needed.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { browser: "Chrome", secureContext: true },
    },
    {
      id: "check-camera-permission",
      label: "Camera permission",
      description: "Confirms the browser has camera permission before joining stage or backstage.",
      status: "pass",
      severity: "high",
      recommendedAction: "No action needed.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
    },
    {
      id: "check-microphone-permission",
      label: "Microphone permission",
      description: "Confirms microphone access and detects input signal.",
      status: "warn",
      severity: "critical",
      recommendedAction: "Ask speaker to select the correct microphone and repeat the audio test.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { inputLevel: 12, expectedMinimum: 25 },
    },
    {
      id: "check-speaker-output",
      label: "Speaker output",
      description: "Confirms user can hear a test tone or stage audio sample.",
      status: "pending",
      severity: "high",
      recommendedAction: "Run manual speaker output test before rehearsal.",
    },
    {
      id: "check-network",
      label: "Network quality",
      description: "Tracks latency, packet loss, and connection stability.",
      status: "warn",
      severity: "critical",
      recommendedAction: "Move speaker to wired internet or open the white-label backup room only if in-platform recovery fails.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { latencyMs: 142, packetLossPercent: 2.7 },
    },
    {
      id: "check-recording",
      label: "Recording readiness",
      description: "Confirms recording hook/status for rooms that require replay.",
      status: "skipped",
      severity: "medium",
      recommendedAction: "Recording is mock-only until real provider integration.",
    },
  ],
  devices: [
    {
      id: "device-camera",
      kind: "camera",
      label: "Camera preview",
      status: "pass",
      details: "Camera permission granted. Preview placeholder active.",
      recommendedAction: "Confirm framing and lighting with speaker.",
    },
    {
      id: "device-microphone",
      kind: "microphone",
      label: "Microphone input",
      status: "warn",
      details: "Input is detected but below target level.",
      recommendedAction: "Switch microphone, raise input gain, or move closer.",
    },
    {
      id: "device-speaker",
      kind: "speaker",
      label: "Speaker output",
      status: "pending",
      details: "Manual confirmation required.",
      recommendedAction: "Play test tone and ask operator to confirm.",
    },
    {
      id: "device-network",
      kind: "network",
      label: "Network quality",
      status: "warn",
      details: "Latency and packet loss are above ideal show conditions.",
      recommendedAction: "Use wired internet or prepare fallback room.",
    },
  ],
  rooms: [
    {
      id: "room-main-stage",
      eventId: "event-summit",
      roomName: "Main Stage",
      roomType: "main_stage",
      provider: "mock",
      status: "warn",
      joinTestStatus: "pass",
      audioStatus: "warn",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 142,
      packetLossPercent: 2.7,
      recommendedAction: "Run speaker audio test again and open the white-label backup room only if in-platform recovery fails link.",
    },
    {
      id: "room-backstage",
      eventId: "event-summit",
      roomName: "Backstage",
      roomType: "backstage",
      provider: "mock",
      status: "pass",
      joinTestStatus: "pass",
      audioStatus: "pass",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 88,
      packetLossPercent: 0.4,
      recommendedAction: "No action needed.",
    },
    {
      id: "room-breakout-a",
      eventId: "event-summit",
      roomName: "Breakout A",
      roomType: "breakout_session",
      provider: "mock",
      status: "pending",
      joinTestStatus: "pending",
      audioStatus: "pending",
      videoStatus: "pending",
      recordingStatus: "skipped",
      recommendedAction: "Run preflight before opening room.",
    },
    {
      id: "room-clarity-booth",
      eventId: "event-summit",
      roomName: "Clarity Booth",
      roomType: "sponsor_booth",
      provider: "mock",
      status: "pass",
      joinTestStatus: "pass",
      audioStatus: "pass",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 72,
      packetLossPercent: 0.1,
      recommendedAction: "No action needed.",
    },
  ],
  incidents: [
    {
      id: "incident-audio-low",
      eventId: "event-summit",
      title: "Main stage speaker audio low",
      severity: "high",
      status: "monitoring",
      summary: "Audio input detected but level is below recommended threshold.",
      platformRecoveryRequired: false,
      createdAt: "2026-05-18T16:12:00.000Z",
    },
    {
      id: "incident-network",
      eventId: "event-summit",
      title: "Speaker network instability",
      severity: "critical",
      status: "open",
      summary: "Packet loss above safe show threshold for main stage guest.",
      platformRecoveryRequired: true,
      createdAt: "2026-05-18T16:13:00.000Z",
    },
  ],
};
