import { mockData as runtimeSeedData, mockUsers as runtimeSeedUsers } from "@/lib/mock/mockData";
import { getEventSetupDraftByEventCode } from "@/services/events/eventDraftStore";

type SeedEvent = (typeof runtimeSeedData.events)[number];
type SeedSession = (typeof runtimeSeedData.sessions)[number];
type SeedSpeaker = (typeof runtimeSeedData.speakers)[number];
type SeedSponsor = (typeof runtimeSeedData.sponsors)[number];
type SeedBooth = (typeof runtimeSeedData.sponsorBooths)[number];
type SeedRunOfShow = (typeof runtimeSeedData.runOfShowSegments)[number];

function dynamicDraftEvent(eventId: string): SeedEvent | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return {
    ...runtimeSeedData.events[0],
    id: draft.eventCode,
    clientId: runtimeSeedData.clients[0]?.id || "client-nova",
    name: draft.eventName,
    slug: draft.eventCode,
    eventType: "virtual_summit",
    status: "registration_open",
    startAt: draft.eventDate ? `${draft.eventDate}T15:00:00.000Z` : runtimeSeedData.events[0].startAt,
    endAt: draft.eventDate ? `${draft.eventDate}T20:00:00.000Z` : runtimeSeedData.events[0].endAt,
    description: `${draft.eventName} generated by the operator setup flow.`,
    internalGoal: "Prove the newly-created event lifecycle using real operator-created runtime data.",
    clientFacingGoal: `Operate ${draft.eventName} with registration, venue, roles, and video readiness.`,
    registrationEnabled: true,
    venueEnabled: true,
  } as SeedEvent;
}

function dynamicDraftSessions(eventId: string): SeedSession[] | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return [
    { ...runtimeSeedData.sessions[0], id: `${draft.eventCode}-main-stage`, eventId: draft.eventCode, name: `${draft.eventName} Main Stage`, description: "Generated main-stage session for the newly-created event.", startAt: draft.eventDate ? `${draft.eventDate}T15:00:00.000Z` : runtimeSeedData.sessions[0].startAt, endAt: draft.eventDate ? `${draft.eventDate}T16:00:00.000Z` : runtimeSeedData.sessions[0].endAt },
    { ...runtimeSeedData.sessions[0], id: `${draft.eventCode}-operator-briefing`, eventId: draft.eventCode, name: "Operator briefing", description: "Generated operator briefing session for the newly-created event.", startAt: draft.eventDate ? `${draft.eventDate}T16:15:00.000Z` : runtimeSeedData.sessions[0].startAt, endAt: draft.eventDate ? `${draft.eventDate}T17:00:00.000Z` : runtimeSeedData.sessions[0].endAt },
  ] as SeedSession[];
}

function dynamicDraftSpeakers(eventId: string): SeedSpeaker[] | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return [{ ...runtimeSeedData.speakers[0], id: `${draft.eventCode}-speaker`, eventId: draft.eventCode, name: "Playwright Speaker", company: draft.clientName, title: "Featured Speaker" }] as SeedSpeaker[];
}

function dynamicDraftSponsors(eventId: string): SeedSponsor[] | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return [{ ...runtimeSeedData.sponsors[0], id: `${draft.eventCode}-sponsor`, eventId: draft.eventCode, name: "Playwright Sponsor", websiteUrl: "https://westpeek.live" }] as SeedSponsor[];
}

function dynamicDraftSponsorBooths(eventId: string): SeedBooth[] | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return [{ ...runtimeSeedData.sponsorBooths[0], id: `${draft.eventCode}-booth`, eventId: draft.eventCode, sponsorId: `${draft.eventCode}-sponsor`, name: "Playwright Sponsor Booth", description: "Generated sponsor booth for the newly-created event." }] as SeedBooth[];
}

function dynamicDraftRunOfShow(eventId: string): SeedRunOfShow[] | undefined {
  const draft = getEventSetupDraftByEventCode(eventId);
  if (!draft) return undefined;
  return [
    { ...runtimeSeedData.runOfShowSegments[0], id: `${draft.eventCode}-opening`, eventId: draft.eventCode, segmentTitle: "Opening remarks", publicTitle: "Opening remarks", startAt: draft.eventDate ? `${draft.eventDate}T15:00:00.000Z` : runtimeSeedData.runOfShowSegments[0].startAt },
    { ...runtimeSeedData.runOfShowSegments[0], id: `${draft.eventCode}-streamyard-check`, eventId: draft.eventCode, title: "StreamYard to LiveKit check", startAt: draft.eventDate ? `${draft.eventDate}T15:10:00.000Z` : runtimeSeedData.runOfShowSegments[0].startAt },
  ] as SeedRunOfShow[];
}

function fallbackRuntimeEvent(eventId: string): SeedEvent {
  const base = runtimeSeedData.events[0];
  const safeEventId = eventId.trim() || base.id;
  const title = safeEventId
    .split(/[-_]+/)
    .filter(Boolean)
    .slice(0, 6)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ") || "Generated Virtual Event";
  return {
    ...base,
    id: safeEventId,
    slug: safeEventId,
    name: title,
    status: "registration_open",
    registrationEnabled: true,
    venueEnabled: true,
    description: `${title} generated from the requested venue event id.`,
    internalGoal: "Preserve requested runtime event identity instead of silently falling back to another event.",
    clientFacingGoal: `Operate ${title} with registration, venue, roles, and video readiness.`,
  } as SeedEvent;
}

export function getRuntimeData() {
  return runtimeSeedData;
}

export function getCurrentRuntimeUser() {
  return runtimeSeedUsers[0];
}

export function getRuntimeUsers() {
  return runtimeSeedUsers;
}

export function getEvent(eventId: string) {
  const normalizedEventId = eventId === "demo" ? "event-summit" : eventId;
  return runtimeSeedData.events.find((event) => event.id === normalizedEventId || event.slug === normalizedEventId) ?? dynamicDraftEvent(normalizedEventId) ?? fallbackRuntimeEvent(normalizedEventId);
}

export function getClient(clientId: string) {
  return runtimeSeedData.clients.find((client) => client.id === clientId) ?? runtimeSeedData.clients[0];
}

export function getEventClient(eventId: string) {
  const event = getEvent(eventId);
  return getClient(event.clientId);
}

export function getClientBySlug(slug: string) {
  return runtimeSeedData.clients.find((client) => client.slug === slug) ?? runtimeSeedData.clients[0];
}

export function getEventBySlug(slug: string) {
  return runtimeSeedData.events.find((event) => event.slug === slug) ?? dynamicDraftEvent(slug) ?? fallbackRuntimeEvent(slug);
}

export function getTasksForEvent(eventId: string) {
  return runtimeSeedData.tasks.filter((task) => task.eventId === eventId);
}

export function getRunOfShowForEvent(eventId: string) {
  const seeded = runtimeSeedData.runOfShowSegments
    .filter((segment) => segment.eventId === eventId)
    .sort((a, b) => a.startAt.localeCompare(b.startAt));
  return seeded.length ? seeded : dynamicDraftRunOfShow(eventId) || [];
}

export function getApprovalsForEvent(eventId: string) {
  return runtimeSeedData.approvals.filter((approval) => approval.eventId === eventId);
}

export function getAssetsForEvent(eventId: string) {
  return runtimeSeedData.assets.filter((asset) => asset.eventId === eventId || !asset.eventId);
}

export function getSpeakersForEvent(eventId: string) {
  const seeded = runtimeSeedData.speakers.filter((speaker) => speaker.eventId === eventId);
  return seeded.length ? seeded : dynamicDraftSpeakers(eventId) || [];
}

export function getSponsorsForEvent(eventId: string) {
  const seeded = runtimeSeedData.sponsors.filter((sponsor) => sponsor.eventId === eventId);
  return seeded.length ? seeded : dynamicDraftSponsors(eventId) || [];
}

export function getSponsorBoothsForEvent(eventId: string) {
  const seeded = runtimeSeedData.sponsorBooths.filter((booth) => booth.eventId === eventId);
  return seeded.length ? seeded : dynamicDraftSponsorBooths(eventId) || [];
}

export function getSessionsForEvent(eventId: string) {
  const seeded = runtimeSeedData.sessions.filter((session) => session.eventId === eventId);
  return seeded.length ? seeded : dynamicDraftSessions(eventId) || [];
}

export function getContractorAssignmentsForEvent(eventId: string) {
  return runtimeSeedData.contractorAssignments.filter((assignment) => assignment.eventId === eventId);
}

export function getVendorAssignmentsForEvent(eventId: string) {
  return runtimeSeedData.vendorAssignments.filter((assignment) => assignment.eventId === eventId);
}

export function getAnalyticsForEvent(eventId: string) {
  return runtimeSeedData.analyticsEvents.filter((event) => event.eventId === eventId);
}
