const fs = require("fs");
const path = require("path");

function fail(message) {
  console.error("sync_required_secrets_manifest: FAIL — " + message);
  process.exit(1);
}
function readJson(file) {
  if (!fs.existsSync(file)) fail("missing " + file);
  return JSON.parse(fs.readFileSync(file, "utf8"));
}
function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n");
}
function accessKeys() {
  const access = readJson("data/access/event-access-config.json");
  const keys = new Set();
  for (const eventConfig of Object.values(access.events || {})) {
    if (eventConfig.crewPasswordEnvKey) keys.add(eventConfig.crewPasswordEnvKey);
    for (const item of eventConfig.specialGuestCodes || []) {
      if (item.envKey) keys.add(item.envKey);
    }
  }
  return Array.from(keys).sort();
}

const registryPath = "deployment/env-var-registry.json";
const registry = readJson(registryPath);
const derivedRequired = new Set([...(registry.requiredProductionEnv || []), ...accessKeys()]);
const derivedCloudflare = new Set([...(registry.cloudflareSecretKeys || []), ...accessKeys()]);

registry.requiredProductionEnv = Array.from(derivedRequired).sort();
registry.cloudflareSecretKeys = Array.from(derivedCloudflare).sort();
writeJson(registryPath, registry);

const manifestPath = "deployment/cloudflare-required-secrets.json";
const manifest = fs.existsSync(manifestPath) ? readJson(manifestPath) : {};
manifest.workerName = registry.workerName || "west-peek-live";
manifest.liveSmokeBaseUrl = registry.liveSmokeBaseUrl || "https://west-peek-live.seq-taylor.workers.dev";
manifest.requiredSecrets = registry.cloudflareSecretKeys;
manifest.demoDefaults = {
  ...(manifest.demoDefaults || {}),
  CREW_ACCESS_PASSWORD: "CrewAccess-2026!",
  EVENT_DEMO_SPEAKER_CODE: "SpeakerGuest-2026!",
  EVENT_DEMO_SPONSOR_CODE: "SponsorGuest-2026!",
  EVENT_DEMO_VIP_CODE: "VIPGuest-2026!",
  EVENT_DEMO_CLIENT_CODE: "VIPGuest-2026!",
  EVENT_DEMO_CREW_LITE_CODE: "CrewAccess-2026!",
  AGENCY_EVENT_OS_RUNTIME_STORE: "file",
  ALLOW_FILE_RUNTIME_STORE_IN_PRODUCTION: "true",
  VIDEO_PROVIDER: "livekit",
  DAILY_FALLBACK_ENABLED: "true",
  DAILY_API_BASE_URL: "https://api.daily.co/v1"
};
writeJson(manifestPath, manifest);

const envExampleValues = {
  NEXT_PUBLIC_APP_URL: "https://westpeek.live",
  AUTH_SESSION_COOKIE_NAME: "agency_event_os_session",
  V5_CREW_COOKIE_NAME: "wpl_crew_access",
  V5_SPECIAL_GUEST_COOKIE_NAME: "wpl_guest_access",
  EMAIL_FROM: "West Peek Live <hello@westpeek.live>",
  EMAIL_REPLY_TO: "support@westpeek.live",
  VIDEO_PROVIDER: "livekit",
  DAILY_API_BASE_URL: "https://api.daily.co/v1",
  DAILY_FALLBACK_ENABLED: "true",
  AGENCY_EVENT_OS_RUNTIME_STORE: "supabase",
  ALLOW_FILE_RUNTIME_STORE_IN_PRODUCTION: "false"
};
const lines = [
  "# West Peek Live environment registry example.",
  "# Never commit real secrets. Production values must be set in Cloudflare Worker secrets/vars.",
  "# Generated by scripts/sync_required_secrets_manifest.js.",
  ""
];
for (const key of registry.requiredProductionEnv) {
  lines.push(`${key}=${envExampleValues[key] || ""}`);
}
lines.push("", "# Optional/dev-only values. These are not production-complete signals.");
for (const key of registry.optionalDevEnv || []) lines.push(`${key}=`);
fs.writeFileSync(".env.example", lines.join("\n") + "\n");

console.log("sync_required_secrets_manifest: PASS");
console.log("Required production env keys: " + registry.requiredProductionEnv.length);
console.log("Cloudflare required secret names: " + registry.cloudflareSecretKeys.length);
