import type { CsvExport, EventReport, EventReportMetric, EventReportSection, EventReportType } from "@/types/reports";
type EventReportInput = { id:string; agencyId:string; clientId?:string; eventId:string; reportType:EventReportType; title:string; metrics:Record<string,string|number> };
const humanize=(key:string)=>key.replace(/[_-]+/g," ").replace(/\b\w/g,(l)=>l.toUpperCase());
const toMetrics=(m:Record<string,string|number>):EventReportMetric[]=>Object.entries(m).map(([k,v])=>({label:humanize(k),value:v}));
export function buildEventReport(input:EventReportInput):EventReport { const metrics=toMetrics(input.metrics); const sections:EventReportSection[]=[{sectionKey:"overview",title:"Overview",summary:input.title,metrics:metrics.slice(0,Math.ceil(metrics.length/2)),sortOrder:0},{sectionKey:"performance",title:"Performance",summary:"Key event performance indicators.",metrics:metrics.slice(Math.ceil(metrics.length/2)),sortOrder:1},{sectionKey:"next_steps",title:"Next Steps",summary:"Review outcomes and assign follow-up actions.",metrics:[],sortOrder:2}]; return {id:input.id,agencyId:input.agencyId,clientId:input.clientId,eventId:input.eventId,reportType:input.reportType,title:input.title,status:"generated",sections}; }
export function buildSponsorReport(input:{agencyId:string;eventId:string;sponsorId:string;sponsorName:string;boothVisits:number;leads:number;ctaClicks:number}):EventReport{return buildEventReport({id:`sponsor-${input.sponsorId}-${input.eventId}`,agencyId:input.agencyId,eventId:input.eventId,reportType:"sponsor",title:`${input.sponsorName} Sponsor Report`,metrics:{booth_visits:input.boothVisits,leads:input.leads,cta_clicks:input.ctaClicks}})}
export function buildTestingIncidentReport(input:{agencyId:string;eventId:string;incidentCount:number;testingFailureCount:number}):EventReport{return buildEventReport({id:`testing-${input.eventId}`,agencyId:input.agencyId,eventId:input.eventId,reportType:"testing_incident",title:"Testing and Incident Report",metrics:{incidents:input.incidentCount,testing_failures:input.testingFailureCount}})}
const esc=(v:unknown)=>{const t=v==null?"":String(v);return /[",\n\r]/.test(t)?`"${t.replace(/"/g,'""')}"`:t};
export function buildCsvExport(input:{fileName:string;rows:Array<Record<string,unknown>>}):CsvExport{const headers=Array.from(new Set(input.rows.flatMap(r=>Object.keys(r))));const lines=[headers.map(esc).join(",")];for(const row of input.rows)lines.push(headers.map(h=>esc(row[h])).join(","));return{fileName:input.fileName,contentType:"text/csv",body:`${lines.join("\n")}\n`}}
